apiVersion: apps/v1
kind: Deployment

metadata:
  name: drift-monitor

spec:
  replicas: 1

  selector:
    matchLabels:
      app: drift-monitor

  template:
    metadata:
      labels:
        app: drift-monitor

    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: drift-monitor

          image: ghcr.io/arpanneupane75/churn-monitor:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8001

          readinessProbe:
            httpGet:
              path: /metrics
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /metrics
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "512Mi"
              cpu: "500m"